"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var round_hole_1 = require("./round_hole");
var round_peg_1 = require("./round_peg");
var square_peg_1 = require("./square_peg");
var angular_peg_1 = require("./angular_peg");
var adapter_1 = require("./adapter");
var roundHoleS = new round_hole_1.RoundHole(5);
var roundHoleM = new round_hole_1.RoundHole(10);
var roundHoleL = new round_hole_1.RoundHole(350);
var roundPeg = new round_peg_1.RoundPeg(5);
var squarePeg = new adapter_1.Adapter(new square_peg_1.SquarePeg(5));
var angularPeg = new adapter_1.Adapter(new angular_peg_1.AngularPeg(5, 5, 5));
roundHoleS.fits(roundPeg);
roundHoleS.fits(squarePeg);
roundHoleS.fits(angularPeg);
roundHoleM.fits(roundPeg);
roundHoleM.fits(squarePeg);
roundHoleM.fits(angularPeg);
roundHoleL.fits(roundPeg);
roundHoleL.fits(squarePeg);
roundHoleL.fits(angularPeg);
