"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var client_1 = require("./client");
var china_1 = require("./china");
var director_1 = require("./director");
var director = new director_1.Director();
var dongfangyuejuBuilder = new china_1.China();
director.setBuilder(dongfangyuejuBuilder);
director.dongfangyueju();
var dongfangyueju = dongfangyuejuBuilder.getHouse();
client_1.client(dongfangyueju);
var jingyaoBuilder = new china_1.China();
director.setBuilder(jingyaoBuilder);
director.jingyao();
var jingyao = jingyaoBuilder.getHouse();
client_1.client(jingyao);
var tangchenyipinBuilder = new china_1.China();
director.setBuilder(tangchenyipinBuilder);
director.tangchenyipin();
var tangchenyipin = tangchenyipinBuilder.getHouse();
client_1.client(tangchenyipin);
