"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tv_1 = require("./tv");
var radio_1 = require("./radio");
var remote_1 = require("./remote");
var advanced_remote_1 = require("./advanced_remote");
var tv = new tv_1.Tv();
var radio = new radio_1.Radio();
var remote = new remote_1.Remote(radio);
var advancedRemote = new advanced_remote_1.AdvancedRemote(tv);
console.log('---- radio start ----');
console.log('toggle power', remote.togglePower());
console.log('volume down', remote.volumeDown());
console.log('volume down', remote.volumeDown());
console.log('volume up', remote.volumeUp());
console.log('volume up', remote.volumeUp());
console.log('channel down', remote.channelDown());
console.log('channel down', remote.channelDown());
console.log('channel up', remote.channelUp());
console.log('---- radio end ----');
console.log();
console.log('---- tv start ----');
console.log('toggle power', advancedRemote.togglePower());
console.log('volume down', advancedRemote.volumeDown());
console.log('volume down', advancedRemote.volumeDown());
console.log('volume up', advancedRemote.volumeUp());
console.log('mute', advancedRemote.mute());
console.log('volume up', advancedRemote.volumeUp());
console.log('channel down', advancedRemote.channelDown());
console.log('channel down', advancedRemote.channelDown());
console.log('channel up', advancedRemote.channelUp());
console.log('---- tv end ----');
